// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qmizmidbkambhxxyjueu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtaXptaWRia2FtYmh4eHlqdWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2MDQyMzAsImV4cCI6MjA4NzE4MDIzMH0.cel1Wy5dKb33p6nnQSxF39xH1CGIxyeyXa2VgNJ7qgQ";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);